"""autogenerated by genpy from lab2/MovementRaw.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class MovementRaw(genpy.Message):
  _md5sum = "b361f62b14c05eacc4779080e1ae1bd4"
  _type = "lab2/MovementRaw"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
float32 xL	#Rotational x vector component
float32 yL      #Rotational y vector component
float32 xR	#Translational x vector component
float32 yR	#Translational y vector component
float32 bumperL #Left analog bumper/trigger
float32 bumperR #Right analog bumper/trigger
int32 xButton	#X button state from the joystick
int32 bButton   #Y button state from the joystick

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

"""
  __slots__ = ['header','xL','yL','xR','yR','bumperL','bumperR','xButton','bButton']
  _slot_types = ['std_msgs/Header','float32','float32','float32','float32','float32','float32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,xL,yL,xR,yR,bumperL,bumperR,xButton,bButton

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MovementRaw, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.xL is None:
        self.xL = 0.
      if self.yL is None:
        self.yL = 0.
      if self.xR is None:
        self.xR = 0.
      if self.yR is None:
        self.yR = 0.
      if self.bumperL is None:
        self.bumperL = 0.
      if self.bumperR is None:
        self.bumperR = 0.
      if self.xButton is None:
        self.xButton = 0
      if self.bButton is None:
        self.bButton = 0
    else:
      self.header = std_msgs.msg.Header()
      self.xL = 0.
      self.yL = 0.
      self.xR = 0.
      self.yR = 0.
      self.bumperL = 0.
      self.bumperR = 0.
      self.xButton = 0
      self.bButton = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6f2i.pack(_x.xL, _x.yL, _x.xR, _x.yR, _x.bumperL, _x.bumperR, _x.xButton, _x.bButton))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.xL, _x.yL, _x.xR, _x.yR, _x.bumperL, _x.bumperR, _x.xButton, _x.bButton,) = _struct_6f2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_6f2i.pack(_x.xL, _x.yL, _x.xR, _x.yR, _x.bumperL, _x.bumperR, _x.xButton, _x.bButton))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.xL, _x.yL, _x.xR, _x.yR, _x.bumperL, _x.bumperR, _x.xButton, _x.bButton,) = _struct_6f2i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_6f2i = struct.Struct("<6f2i")
